export { type ILembagaWithKategoriDTO } from "./model/lembaga"
export { type IFormLembagaData } from "./model/lembagaResponse"
export { type ILembagaBody } from "./model/lembagaRequest"
export { type ILembagaResponseData } from "./model/lembagaResponse"
export { AddLembagaForm } from "./components/AddLembagaForm"
export { LembagaRepository } from "./repository/LembagaRepo"