export interface ActivityForm {
    activityName: string,
    activityGoal: string,
    activityField: string,
    location: string,
    activityDescription: string,
    activityStatus: string,
    successIndicator: string,
    outputTarget: string,
    startDate: string,
    endDate: string,
    logistics: string,
    activityMethod: string,
    activityDocument: string,
}